[package]
name = "polkadot-service"
version = "0.7.19"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parking_lot = "0.9.0"
serde = { version = "1.0.102", features = ["derive"] }
lazy_static = "1.4.0"
log = "0.4.8"
futures = "0.3.1"
slog = "2.5.2"
hex-literal = "0.2.1"
av_store = { package = "polkadot-availability-store", path = "../availability-store" }
consensus = { package = "polkadot-validation", path = "../validation" }
polkadot-primitives = { path = "../primitives" }
polkadot-runtime = { path = "../runtime/polkadot" }
kusama-runtime = { path = "../runtime/kusama" }
polkadot-network = { path = "../network"  }
polkadot-rpc = { path = "../rpc" }
sp-io = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sp-api = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sc-client = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sc-client-api = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sc-client-db = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sc-executor = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sc-network = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
consensus_common = { package = "sp-consensus", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
grandpa = { package = "sc-finality-grandpa", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
grandpa_primitives = { package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
inherents = { package = "sp-inherents", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
service = { package = "sc-service", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff", default-features = false }
telemetry = { package = "sc-telemetry", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sc-keystore = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
pallet-babe = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
pallet-staking = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
im-online = { package = "pallet-im-online", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
authority-discovery = { package = "sc-authority-discovery", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
authority-discovery-primitives = { package = "sp-authority-discovery", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
babe = { package = "sc-consensus-babe", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
system_rpc_runtime_api = { package = "frame-system-rpc-runtime-api", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
codec = { package = "parity-scale-codec", version = "1.1.0" }
sp-session = { git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }
sp-offchain = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", rev = "26e37ff685819646633f5246419c03c02df81dff" }

[features]
default = ["rocksdb"]
rocksdb = ["service/rocksdb"]
